

const FETCH_TRIVIA_START = 'FETCH_TRIVIA_START'
const FETCH_TRIVIA_SUCCESS = 'FETCH_TRIVIA_SUCCESS'
const FETCH_TRIVIA_FAILURE = 'FETCH_TRIVIA_FAILURE'
const SET_TRIVIA_ANSWERS = 'SET_TRIVIA_ANSWERS'

export { FETCH_TRIVIA_START,FETCH_TRIVIA_SUCCESS, FETCH_TRIVIA_FAILURE,SET_TRIVIA_ANSWERS}
